riemann:
  host: localhost
  port: 5555
  dns_ttl: 120

logger:
  level: WARN

plugins:

  interval: 60

  dummy:
    service: keep alive
    interval: 1

  la:
    service: la
    interval: 1
    states:
      warning: 4
      critical: 10

  disk:
    service: disk
    interval: 1
    states:
      warning: 0.7
      critical: 0.85

  cpu:
    service: cpu usage
    interval: 1
    states:
      warning: 0.7
      critical: 0.85

  memory:
    service: memory
    interval: 1
    states:
      warning: 0.6
      critical: 0.8

  net:
    service: net
    interval: 5
