riemann:
  host: 127.0.0.1
  port: 5555
  proto: auto # auto use tcp + udp(max size 16384), tcp - tcp only

logger:
  level: DEBUG

plugins:

  run_only:
  #  - cpu

  interval: 60

  dummy:
    service: keep alive
    interval: 1

  la:
    service: la
    interval: 1
    states:
      warning: 4
      critical: 10

  disk:
    service: disk
    interval: 1
    states:
      warning: 0.7
      critical: 0.85

  cpu:
    service: cpu usage
    interval: 1
    states:
      warning: 0.7
      critical: 0.85

  memory:
    service: memory
    interval: 1
    states:
      warning: 0.6
      critical: 0.8

  net:
    service: net
    interval: 5
