riemann:
  host: hostname_does_not_exists
  port: 5555
  proto: auto # auto use tcp + udp(max size 16384), tcp - tcp only
  interval: 60 # update interval for all plugins 
  use_fqdn: true

logger:
  level: FATAL

plugins:
  dummy2:
    parent: dummy
    run: false
    interval: 2000